export interface Product {
  id: number;
  name: string;
  sku: string;
  quantity: number;
  minStock: number;
  price: number;
  categoryId: string;
  locationId: string;
  description: string;
  brand: string;
  specification: string;
  unitOfMeasure: string;
  createdAt: string;
}

export interface Category {
  id: string;
  name: string;
}

export interface Location {
  id: string;
  name: string;
}

export interface HistoryEntry {
  id: number;
  productId: number | null;  // Nullable - becomes null when product is deleted (history preserved)
  productName?: string; // Product name fetched from JOIN - avoids "Unknown Product" issue
  action: 'created' | 'stock_in' | 'stock_out' | 'deleted' | 'updated';
  quantity: number;
  notes: string;
  timestamp: string;
  // Contact person - label changes based on action: "Received By" for stock_in, "Issued To" for stock_out
  contactPerson?: string;
  pricePerUnit?: number;
  date?: string;
  unitOfMeasure?: string; // Unit of measure stored for audit trail
}

export type HistoryActionFilter = 'all' | 'stock_in' | 'stock_out';
export type HistoryDateRangeFilter = 'all' | 'today' | 'yesterday' | 'weekly' | 'current_month' | 'previous_month' | '3_months' | 'custom';

export interface HistoryFilters {
  action: HistoryActionFilter;
  dateRange: HistoryDateRangeFilter;
  searchTerm: string;
}

export type TabType = 'dashboard' | 'products' | 'history' | 'settings' | 'extinguishers';

export interface ProductFormData {
  name: string;
  sku: string;
  quantity: number;
  minStock: number;
  price: number;
  categoryId: string;
  locationId: string;
  description: string;
  brand: string;
  specification: string;
  unitOfMeasure: string;
}

export interface StorageItem {
  value: string;
}

// ============================================================
// Fire Extinguishers
// ============================================================

export interface FireExtinguisher {
  id: number;
  area: string;
  location: string;
  extinguisherNo: string;
  /**
   * Composite unique ID derived from AREA + LOCATION + EXTINGUISHER NO.
   * Generated by the database (a STORED generated column), never by the client,
   * so it cannot drift from the values it is derived from.
   */
  uniqueKey: string;
  type: string;
  capacity: string;
  pressure: string;
  inspectionTag: string;
  safetyPin: string;
  refilledDate: string | null;
  refillingDueDate: string | null;
  remarks: string;
  sourceSheet: string;
  createdAt: string;
  updatedAt: string;
}

export interface FireExtinguisherFormData {
  area: string;
  location: string;
  extinguisherNo: string;
  type: string;
  capacity: string;
  pressure: string;
  inspectionTag: string;
  safetyPin: string;
  refilledDate: string;
  refillingDueDate: string;
  remarks: string;
}

export interface FireExtinguisherHistoryEntry {
  id: number;
  extinguisherId: number | null; // Null once the record is deleted (history preserved)
  extinguisherKey: string;
  action: 'created' | 'updated' | 'deleted' | 'imported';
  changes: string;
  notes: string;
  createdAt: string;
}

/** Derived from refillingDueDate, not stored. */
export type ExtinguisherStatus = 'all' | 'overdue' | 'due_soon' | 'ok' | 'no_date';

export interface FireExtinguisherFilters {
  searchTerm: string;
  area: string;
  type: string;
  status: ExtinguisherStatus;
}

export type ExtinguisherSortField = 'refilling_due_date' | 'refilled_date' | 'area' | 'location';

export interface FireExtinguisherSort {
  field: ExtinguisherSortField;
  ascending: boolean;
}

export interface FireExtinguisherSummary {
  total: number;
  overdue: number;
  dueSoon: number;
  ok: number;
  noDate: number;
}

/** One row parsed from an uploaded sheet, ready for the bulk upsert RPC. */
export interface FireExtinguisherImportRow {
  area: string;
  location: string;
  extinguisher_no: string;
  type: string;
  capacity: string;
  pressure: string;
  inspection_tag: string;
  safety_pin: string;
  refilled_date: string | null;
  refilling_due_date: string | null;
  remarks: string;
  source_sheet: string;
}

export interface FireExtinguisherImportFileResult {
  fileName: string;
  /** Rows accepted from this file and sent to the upsert. */
  parsed: number;
  /** Rows rejected during parsing (missing key columns, bad structure). */
  skipped: number;
}

export interface FireExtinguisherImportResult {
  success: boolean;
  totalInserted: number;
  totalUpdated: number;
  files: FireExtinguisherImportFileResult[];
  errors: string[];
  warnings: string[];
}
